### PR TITLE
Gol example

### PR DESCRIPTION
**Pull request by purpledan**
I have been working on a little program that I thought could be a good demo.

It is an implementation of Conway's game of life, using termbox2 and nothing else.

The only feature I still need to implement is that of resizing the game board along with terminal window.

Let me know what you think.

### CODE REVIEW

**Comment by git-bruh** [comment]
You forgot to srand

**Comment by purpledan** [comment]
On purpose for testing reasons, I could just srand with time for now. Will figure out something more elegant later.

**Comment by adsr** [comment]
Thanks. See if you can get resize working and I'll merge it.

**Comment by purpledan** [comment]
I have a rough working solution, but I am going to spend a couple of days cleaning it up. Thank you

**Comment by purpledan** [comment]
I haven't been working on this for much since my last update, had been busy with uni work. I am still going to finish it up over December or so.

**Comment by adsr** [comment]
Closing due to staleness. Feel free to reopen.

**Pull request closed without merging**
